host_label: host
command_label: responder-cmd
ssh_key: /var/lib/user/.ssh/id_rsa
responders:
  - match:
      - alertname: node_load1
    command: uptime
  - match:
      - alertname: http_down
    command: systemctl restart apache2
